### ISSUE TITLE
Not an editor command

### ISSUE THREAD

**Issue by Demianeen** [henrique-smr/nx.nvim#1]
I would like to try plugin, but each time I run commands like `NxFZFListProjects` or `NxFZFListPlugins` I get error that they are not an editor commands.
https://github.com/henrique-smr/nx.nvim/assets/51330172/62b6fb0d-f6b9-4a13-bf4f-bb81cc4eab1c

My lazy config is super simple:
```lua
{
  'henrique-smr/nx.nvim',
  dependencies = {
    'ibhagwan/fzf-lua',
    'ldelossa/litee.nvim',
  }
}
```

What can this be? This is very promising plugin, so hopefully we will find a solution

**Comment by henrique-smr** [comment]
Hello friend. Thank you for using nx.nvim.
You need to call the setup function. Sorry this was not included in the Readme.
Also, I updated the dependencies of the project, so the config would be like this:
```lua
{
   "henrique-smr/nx.nvim",
   dependencies = { 
      "ibhagwan/fzf-lua",
      "MunifTanjim/nui.nvim"
   },
   config = function()
      require("nx").setup()
   end
}
```

**Comment by henrique-smr** [comment]
Please, checkout the updated Readme for more info.

**Comment by Demianeen** [comment]
Thanks, @henrique-smr for pointing out! That was my bad)
